#!/usr/bin/env python3
"""Manage a user-owned, optionally Git-backed ICODE knowledge library."""

from __future__ import annotations

import argparse
import fcntl
import hashlib
import json
import os
import sys
import tempfile
import uuid
from datetime import datetime, timezone
from pathlib import Path

from lint_knowledge_article import ARTICLE_ID, SLUG, load_json, validate


MARKER = "<!-- Generated by ICODE knowledge_library.py; do not edit this file. -->"


class LibraryError(ValueError):
    pass


def global_data_root() -> Path:
    return Path.home() / ".claude" / "icode_data"


def config_path() -> Path:
    return global_data_root() / "knowledge_config.json"


def state_base() -> Path:
    return global_data_root() / "knowledge_state"


def resolve_root(override: str | None = None, *, create_default: bool = False) -> tuple[Path, str]:
    if override:
        selected, origin = Path(override).expanduser(), "argument"
    elif config_path().is_file():
        config = load_json(config_path())
        if config.get("schema_version") != 1 or not isinstance(config.get("library_root"), str):
            raise LibraryError("knowledge config schema is invalid")
        selected, origin = Path(config["library_root"]).expanduser(), "config"
    else:
        selected = global_data_root() / "knowledge"
        origin = "default"
    if not selected.is_absolute():
        raise LibraryError("library root must be an absolute path")
    if selected.exists() and (selected.is_symlink() or not selected.is_dir()):
        raise LibraryError("library root must be a real directory")
    if not selected.exists():
        if origin != "default":
            raise LibraryError(f"library root does not exist: {selected}")
        if create_default:
            selected.mkdir(parents=True, exist_ok=True)
    root = selected.resolve()
    if (root / "SKILL.md").exists() and (root / "steps").exists():
        raise LibraryError("library root points to the ICODE workflow source")
    return root, origin


def private_root(root: Path) -> Path:
    library_id = hashlib.sha256(str(root).encode("utf-8")).hexdigest()[:16]
    target = state_base() / library_id
    if target.resolve().is_relative_to(root.resolve()):
        raise LibraryError("private source storage must be outside the public library")
    return target


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def atomic_write(path: Path, content: bytes, *, private: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        os.fchmod(fd, 0o600 if private else 0o644)
        with os.fdopen(fd, "wb") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def _article_paths(root: Path, volume: str, chapter: str) -> tuple[Path, Path]:
    directory = root / "volumes" / volume / "chapters"
    return directory / f"{chapter}.md", directory / f"{chapter}.meta.json"


def catalog(root: Path) -> list[dict]:
    entries: list[dict] = []
    for metadata in sorted((root / "volumes").glob("*/chapters/*.meta.json")):
        if metadata.is_symlink():
            raise LibraryError(f"metadata is a symlink: {metadata}")
        item = load_json(metadata)
        volume, chapter = metadata.parent.parent.name, metadata.name.removesuffix(".meta.json")
        if not SLUG.fullmatch(volume) or not SLUG.fullmatch(chapter) or item.get("volume") != volume or item.get("chapter") != chapter:
            raise LibraryError(f"metadata identity mismatch: {metadata}")
        article, _ = _article_paths(root, volume, chapter)
        if not article.is_file() or article.is_symlink():
            raise LibraryError(f"chapter missing or symlinked: {article}")
        for key in ("title", "summary", "order", "tags", "related"):
            if key not in item:
                raise LibraryError(f"metadata missing {key}: {metadata}")
        if (not isinstance(item["title"], str) or not item["title"].strip()
                or "\n" in item["title"] or not isinstance(item["summary"], str)
                or not item["summary"].strip() or not isinstance(item["order"], int)
                or isinstance(item["order"], bool) or item["order"] < 0
                or not isinstance(item["tags"], list)
                or not all(isinstance(tag, str) for tag in item["tags"])
                or not isinstance(item["related"], list)
                or not all(isinstance(ref, str) and ARTICLE_ID.fullmatch(ref)
                           for ref in item["related"])):
            raise LibraryError(f"metadata catalog fields are invalid: {metadata}")
        entries.append({**item, "article_path": str(article), "article_sha256": sha(article.read_bytes()),
                        "metadata_sha256": sha(metadata.read_bytes())})
    return entries


def render_indexes(root: Path, entries: list[dict]) -> dict[Path, bytes]:
    by_volume: dict[str, list[dict]] = {}
    for entry in entries:
        by_volume.setdefault(entry["volume"], []).append(entry)
    all_ids = {f"{entry['volume']}/{entry['chapter']}" for entry in entries}
    outputs: dict[Path, bytes] = {}
    overview = [MARKER, "# 知识库目录", "", "按卷浏览通用技术文章。每章均可独立阅读。", ""]
    for volume in sorted(by_volume):
        chapters = sorted(by_volume[volume], key=lambda item: (item["order"], item["chapter"]))
        overview.append(f"- [{volume}](volumes/{volume}/INDEX.md)（{len(chapters)} 章）")
        lines = [MARKER, f"# {volume}", "", "| 顺序 | 章节 | 摘要 |", "|---:|---|---|"]
        for item in chapters:
            title = item["title"].replace("|", "\\|")
            summary = item["summary"].replace("|", "\\|").replace("\n", " ")
            lines.append(f"| {item['order']} | [{title}](chapters/{item['chapter']}.md) | {summary} |")
        related = [(item, ref) for item in chapters for ref in item["related"]]
        if related:
            lines += ["", "## 关联阅读", ""]
            for item, ref in related:
                if ref not in all_ids:
                    raise LibraryError(f"related chapter does not exist: {ref}")
                target_volume, target_chapter = ref.split("/", 1)
                lines.append(f"- {item['title']} → [{ref}](../{target_volume}/chapters/{target_chapter}.md)")
        outputs[root / "volumes" / volume / "INDEX.md"] = ("\n".join(lines) + "\n").encode("utf-8")
    outputs[root / "CATALOG.md"] = ("\n".join(overview) + "\n").encode("utf-8")
    return outputs


def _preflight_outputs(root: Path, paths: list[Path]) -> None:
    for path in paths:
        if path.is_symlink():
            raise LibraryError(f"refuse symlink target: {path}")
        if path.exists() and not path.is_file():
            raise LibraryError(f"refuse non-file target: {path}")
        parent = path.parent
        while parent != root and parent != parent.parent:
            if parent.is_symlink():
                raise LibraryError(f"refuse symlink parent: {parent}")
            parent = parent.parent
        if path.is_file() and path.name in {"CATALOG.md", "INDEX.md"}:
            if not path.read_text(encoding="utf-8").startswith(MARKER):
                raise LibraryError(f"refuse to overwrite hand-written index: {path}")


def publish(root: Path, article_draft: Path, meta_draft: Path, source_draft: Path,
            mode: str, expected_article: str | None, expected_metadata: str | None) -> dict:
    errors = validate(article_draft, meta_draft, source_draft)
    if errors:
        raise LibraryError("candidate validation failed: " + "; ".join(errors))
    meta = load_json(meta_draft)
    volume, chapter = meta["volume"], meta["chapter"]
    article, metadata = _article_paths(root, volume, chapter)
    state = private_root(root)
    state.mkdir(parents=True, exist_ok=True)
    with (state / ".lock").open("a+b") as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        _preflight_outputs(root, [article, metadata])
        existing = article.exists() or metadata.exists()
        if mode == "add" and existing:
            raise LibraryError("chapter already exists; use revise after reading the old chapter")
        if mode == "revise" and (not article.is_file() or not metadata.is_file()):
            raise LibraryError("chapter revision requires both existing files")
        old_article = article.read_bytes() if existing else None
        old_metadata = metadata.read_bytes() if existing else None
        if mode == "revise":
            if not expected_article or not expected_metadata:
                raise LibraryError("revise requires both expected SHA-256 values")
            if sha(old_article) != expected_article or sha(old_metadata) != expected_metadata:
                raise LibraryError("chapter changed since it was read")
            old = json.loads(old_metadata)
            if old.get("volume") != volume or old.get("chapter") != chapter or old.get("created_at") != meta.get("created_at"):
                raise LibraryError("revision must preserve chapter identity and creation time")
        entries = [item for item in catalog(root) if (item["volume"], item["chapter"]) != (volume, chapter)]
        entries.append(meta)
        indexes = render_indexes(root, entries)
        _preflight_outputs(root, list(indexes))
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        run_id = f"{timestamp}-{uuid.uuid4().hex[:8]}"
        source_target = state / "sources" / volume / chapter / f"{run_id}.json"
        backup = state / "history" / volume / chapter / run_id
        new_article = article_draft.read_bytes()
        new_metadata = meta_draft.read_bytes()
        new_source = source_draft.read_bytes()
        if mode == "revise":
            atomic_write(backup / "article.md", old_article, private=True)
            atomic_write(backup / "metadata.json", old_metadata, private=True)
        index_before = {path: path.read_bytes() if path.exists() else None for path in indexes}
        try:
            atomic_write(article, new_article)
            atomic_write(metadata, new_metadata)
            atomic_write(source_target, new_source, private=True)
            for path, content in indexes.items():
                atomic_write(path, content)
        except OSError:
            for path, previous in ((article, old_article), (metadata, old_metadata), *index_before.items()):
                if previous is None:
                    path.unlink(missing_ok=True)
                else:
                    atomic_write(path, previous)
            source_target.unlink(missing_ok=True)
            raise
        return {"ok": True, "mode": mode, "article": str(article), "metadata": str(metadata),
                "private_source": str(source_target), "catalog": str(root / "CATALOG.md"),
                "volume_index": str(root / "volumes" / volume / "INDEX.md"),
                "article_sha256": sha(new_article), "metadata_sha256": sha(new_metadata),
                "backup": str(backup) if mode == "revise" else None, "files_changed": True,
                "committed": False, "pushed": False}


def configure(root_arg: str) -> dict:
    root, _ = resolve_root(root_arg)
    private_root(root)
    path = config_path()
    if path.exists() and path.is_symlink():
        raise LibraryError("refuse symlinked knowledge config")
    content = json.dumps({"schema_version": 1, "library_root": str(root)}, ensure_ascii=False, indent=2).encode("utf-8") + b"\n"
    atomic_write(path, content, private=True)
    return {"ok": True, "config": str(path), "library_root": str(root)}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    p = sub.add_parser("configure", help="Save this user's local library path")
    p.add_argument("--root", required=True)
    p = sub.add_parser("resolve", help="Show the effective library path")
    p.add_argument("--library")
    p = sub.add_parser("catalog", help="List volumes and chapters without writing")
    p.add_argument("--library")
    p = sub.add_parser("publish", help="Save a validated chapter locally; never commit or push")
    p.add_argument("article", type=Path)
    p.add_argument("--metadata", required=True, type=Path)
    p.add_argument("--source", required=True, type=Path)
    p.add_argument("--mode", choices=["add", "revise"], required=True)
    p.add_argument("--library")
    p.add_argument("--expect-article-sha256")
    p.add_argument("--expect-metadata-sha256")
    args = parser.parse_args()
    try:
        if args.command == "configure":
            result = configure(args.root)
        else:
            root, origin = resolve_root(args.library, create_default=args.command == "publish")
            if args.command == "resolve":
                result = {"ok": True, "library_root": str(root), "origin": origin,
                          "private_state": str(private_root(root))}
            elif args.command == "catalog":
                result = {"ok": True, "library_root": str(root), "origin": origin, "chapters": catalog(root)}
            else:
                result = publish(root, args.article, args.metadata, args.source, args.mode,
                                 args.expect_article_sha256, args.expect_metadata_sha256)
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0
    except (LibraryError, OSError, ValueError) as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
